import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Content from "@/components/Content";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>noT3s</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Content />
      </main>
    </>
  );
};

export default Home;
